### ISSUE TITLE
[Crash]: game crashed and the only mod mentioned was enhanced celestials

### ISSUE THREAD

**Issue by kuba26038** [CorgiTaco/Enhanced-Celestials#144]
### Minecraft Version

1.19.2

### Enhanced Celestials Version

Enhanced_Celestials-forge-1.19.2-2.1.0.2

### Mod Loader

Forge

### Mod Loader Version

1.19.2-forge-43.1.47

### What happened?

i was walking around when the game suddently crashed.

### crash-log

[crash-2022-11-11_19.12.07-server.txt](https://github.com/CorgiTaco/Enhanced-Celestials/files/9992555/crash-2022-11-11_19.12.07-server.txt)

### latest.log

[2022-11-11-6.log](https://github.com/CorgiTaco/Enhanced-Celestials/files/9992562/2022-11-11-6.log)

**Comment by CorgiTaco** [comment]
Reports don't mention that Enhanced Celestials is explicitly doing this. Seems to be an issue not related to Enhanced Celestials.

```[11Nov2022 19:12:07.914] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.ReportedException: Accessing LegacyRandomSource from multiple threads
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:870) ~[client-1.19.2-20220805.130853-srg.jar%23319!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%23319!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23319!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%23319!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23319!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalStateException: Accessing LegacyRandomSource from multiple threads
	at net.minecraft.util.ThreadingDetector.m_199417_(ThreadingDetector.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23319!/:?]
	at net.minecraft.world.level.levelgen.LegacyRandomSource.m_64707_(LegacyRandomSource.java:49) ~[client-1.19.2-20220805.130853-srg.jar%23319!/:?]
	at net.minecraft.world.level.levelgen.BitRandomSource.m_188503_(BitRandomSource.java:33) ~[client-1.19.2-20220805.130853-srg.jar%23319!/:?]
	at net.minecraft.util.Mth.m_216287_(Mth.java:937) ~[client-1.19.2-20220805.130853-srg.jar%23319!/:?]
	at net.minecraft.world.level.NaturalSpawner.m_47062_(NaturalSpawner.java:290) ~[client-1.19.2-20220805.130853-srg.jar%23319!/:?]
	at net.minecraft.world.level.NaturalSpawner.m_47045_(NaturalSpawner.java:125) ~[client-1.19.2-20220805.130853-srg.jar%23319!/:?]
	at net.minecraft.world.level.NaturalSpawner.m_47029_(NaturalSpawner.java:117) ~[client-1.19.2-20220805.130853-srg.jar%23319!/:?]
	at net.minecraft.server.level.ServerChunkCache.m_8490_(ServerChunkCache.java:356) ~[client-1.19.2-20220805.130853-srg.jar%23319!/:?]
	at net.minecraft.server.level.ServerChunkCache.m_201698_(ServerChunkCache.java:310) ~[client-1.19.2-20220805.130853-srg.jar%23319!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:285) ~[client-1.19.2-20220805.130853-srg.jar%23319!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[client-1.19.2-20220805.130853-srg.jar%23319!/:?]
	... 5 more```
