### ISSUE TITLE
[STDERR]: java.lang.Throwable 

### ISSUE THREAD

**Issue by xR4YM0ND** [CorgiTaco/Enhanced-Celestials#147]
### Minecraft Version

1.19.2

### Enhanced Celestials Version

2.1.0.2

### Mod Loader

Fabric

### Mod Loader Version

0.14.10

### Bug Severity

Minor

### What happened?

check the lines 1630 - 1680

`at corgitaco.enhancedcelestials.network.LunarContextConstructionPacket.handle(LunarContextConstructionPacket.java:46)
at corgitaco.enhancedcelestials.network.FabricNetworkHandler$ClientProxy.lambda$registerClientReceiver$0(FabricNetworkHandler.java:80)
at net.minecraft.class_1255.redirect$zpn000$redirectExecuteTask(class_1255.java:521)
at net.minecraft.class_1255.method_16075(class_1255.java:131)
at net.minecraft.class_1255.method_5383(class_1255.java:116)
at net.minecraft.class_310.method_1523(class_310.java:1129)
at net.minecraft.class_310.method_1514(class_310.java:768)
at net.minecraft.client.main.Main.method_44604(Main.java:244)
at net.minecraft.client.main.Main.main(Main.java:51)
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)`

### latest.log

https://gist.github.com/SpigotDE/b3844b9c4b249a7cd64d77fad9649b32

**Comment by CorgiTaco** [comment]
Your gist is deleted. But im going to assume you don't have the right version of the mod on your client that the server has

**Comment by xR4YM0ND** [comment]
Yeah its been a year since i posted this

If it still happens i will reopen this issue
