### ISSUE TITLE
[Crash]: on 1.20.1 Forge launch

### ISSUE THREAD

**Issue by MrKashew** [CorgiTaco/Enhanced-Celestials#160]
### Minecraft Version

1.20.1

### Enhanced Celestials Version

5.0.0.1

### Mod Loader

Forge

### Mod Loader Version

47.0.3

### What happened?

crash on launch
https://paste.atlauncher.com/view/edf63131-ed88-4942-a787-68c418e0dfe2

### crash-log

https://paste.atlauncher.com/view/edf63131-ed88-4942-a787-68c418e0dfe2

### latest.log

https://paste.atlauncher.com/view/edf63131-ed88-4942-a787-68c418e0dfe2

**Comment by CorgiTaco** [comment]
Not an enhanced Celestials issue. Seems to be an issue with Geode plus

```
[20/06/2023 22:42:20 PM] Time: 2023-06-20 22:42:20
[20/06/2023 22:42:20 PM] Description: Rendering overlay
[20/06/2023 22:42:20 PM] 
[20/06/2023 22:42:20 PM] java.lang.IllegalArgumentException: No model for layer geode_plus:wrappist_pedestal#main
[20/06/2023 22:42:20 PM] 	at net.minecraft.client.model.geom.EntityModelSet.m_171103_(EntityModelSet.java:17) ~[client-1.20.1-20230612.114412-srg.jar%23834!/:?] 
```

**Comment by MrKashew** [comment]
played around with it some more:
- case 2: removing geode+ still errors, but a different log - with biome makeover logged as well
- case 3: removing geode+ and biome makeover, crashes on create world click
- case 4: by keeping geode+ and biome makeover and instead removing celestials allows minecraft to launch and play fine strangely

**case 3:**
after additionally removing biome makeover I get a successful launch but a crash on create world click with a better report
[crash-2023-06-21_20.38.59-client.txt](https://github.com/CorgiTaco/Enhanced-Celestials/files/11828412/crash-2023-06-21_20.38.59-client.txt)

**case 2:**
https://paste.atlauncher.com/view/4ab1c014-fbab-48a7-ad4a-d7a8cba5d12c
here is for case 2 entire log for reference, here are potentially the more useful sections:
```
Caused by 2: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [enhancedcelestials.forge.mixins.json:world.level.storage.loot.MixinLootTableManager] from phase [DEFAULT] in config [enhancedcelestials.forge.mixins.json] FAILED during APPLY
[21/06/2023 20:36:26 PM] 		at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:636) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
[21/06/2023 20:36:26 PM] 		at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:588) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
[21/06/2023 20:36:26 PM] 		at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
[21/06/2023 20:36:26 PM] 		at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
[21/06/2023 20:36:26 PM] 		at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
[21/06/2023 20:36:26 PM] 		at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
[21/06/2023 20:36:26 PM] 		at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.9.jar:10.0.9+10.0.9+main.dcd20f30] {}
[21/06/2023 20:36:26 PM] 		at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar:?] {}
[21/06/2023 20:36:26 PM] 		at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar:?] {}
[21/06/2023 20:36:26 PM] 		at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar:?] {}
[21/06/2023 20:36:26 PM] 		at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?] {}
[21/06/2023 20:36:26 PM] 		at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
[21/06/2023 20:36:26 PM] 		at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?] {}
[21/06/2023 20:36:26 PM] 		at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
[21/06/2023 20:36:26 PM] 		at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?] {}
[21/06/2023 20:36:26 PM] 		at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
[21/06/2023 20:36:26 PM] 		at party.lemons.biomemakeover.BiomeMakeover.init(BiomeMakeover.java:87) ~[biomemakeover-FORGE-1.20.0-1.10.0.jar%23561!/:?] {re:mixin,re:classloading}
[21/06/2023 20:36:26 PM] 		at party.lemons.biomemakeover.forge.BMForge.<init>(BMForge.java:25) ~[biomemakeover-FORGE-1.20.0-1.10.0.jar%23561!/:?] {re:classloading}
[21/06/2023 20:36:26 PM] 		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
[21/06/2023 20:36:26 PM] 		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
[21/06/2023 20:36:26 PM] 		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
[21/06/2023 20:36:26 PM] 		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
[21/06/2023 20:36:26 PM] 		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
[21/06/2023 20:36:26 PM] 		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.20.1-47.0.14.jar%23894!/:?] {}
[21/06/2023 20:36:26 PM] 		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.1-47.0.14.jar%23893!/:?] {re:mixin}
[21/06/2023 20:36:26 PM] 		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
[21/06/2023 20:36:26 PM] 		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
[21/06/2023 20:36:26 PM] 		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
[21/06/2023 20:36:26 PM] 		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
[21/06/2023 20:36:26 PM] 		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames}
[21/06/2023 20:36:26 PM] 		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames}
[21/06/2023 20:36:26 PM] 		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}
```

```
[21/06/2023 20:36:18 PM] [modloading-worker-0/FATAL] Mixin apply failed enhancedcelestials.forge.mixins.json:world.level.storage.loot.MixinLootTableManager -> net.minecraft.world.level.storage.loot.LootDataManager: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on appendTables could not find any targets matching 'lambda$scheduleElementParse$5' in net.minecraft.world.level.storage.loot.LootDataManager. Using refmap enhancedcelestials.refmap.json [PREINJECT Applicator Phase -> enhancedcelestials.forge.mixins.json:world.level.storage.loot.MixinLootTableManager -> Prepare Injections ->  -> handler$cdp000$appendTables(Lnet/minecraft/server/packs/resources/ResourceManager;Lnet/minecraft/world/level/storage/loot/LootDataType;Ljava/util/Map;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Ljava/util/Map;)V -> Parse]
```
edit: I see #161 , will try that fix

**Comment by CorgiTaco** [comment]
This should be fixed with the latest build on curseforge

**Comment by MrKashew** [comment]
works like a charm woohoo
