### ISSUE TITLE
[Crash]: Missing registry: ResourceKey[minecraft:root / enhancedcelestials:lunar/dimension_settings]

### ISSUE THREAD

**Issue by spoorn** [CorgiTaco/Enhanced-Celestials#165]
### Minecraft Version

1.19.2

### Enhanced Celestials Version

5.0.0.2

### Mod Loader

Fabric

### Mod Loader Version

0.14.21

### What happened?

See error log, happens on server side I believe

### crash-log

[crash-2023-07-18_21.33.03-server.txt](https://github.com/CorgiTaco/Enhanced-Celestials/files/12091092/crash-2023-07-18_21.33.03-server.txt)

### latest.log

N/A

**Comment by Withersip** [comment]
**I figured out the reason I was crashing is due to incompatibility with "bclib". (The library mod for better nether/better end)**

Also getting this on Fabric 1.20.1. Game crashed when loading in world

Heres the crash in my latest.log:
[16:39:06] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.IllegalStateException: Missing registry: ResourceKey[minecraft:root / enhancedcelestials:lunar/dimension_settings]
	at net.minecraft.class_5455.method_30534(class_5455.java:26) ~[client-intermediary.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.class_5455.method_30530(class_5455.java:26) ~[client-intermediary.jar:?]
	at corgitaco.enhancedcelestials.core.EnhancedCelestialsContext.forLevel(EnhancedCelestialsContext.java:34) ~[Enhanced_Celestials-fabric-1.20.1-5.0.0.2.jar:?]
	at net.minecraft.class_3218.handler$bpa000$enhancedcelestials$injectLunarContext(class_3218.java:6730) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.<init>(class_3218.java:263) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java:359) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:324) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3823(class_1132.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:646) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Hansynily** [comment]
It was the new fabric-api-0.86.0+1.20.1.jar for me. I had to rollback to 0.85.0 version to work with bclib and EC

java.lang.IllegalStateException: Missing registry: ResourceKey[minecraft:root / enhancedcelestials:lunar/dimension_settings]
	at net.minecraft.class_5455.method_30534(class_5455.java:26)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at net.minecraft.class_5455.method_30530(class_5455.java:26)
	at corgitaco.enhancedcelestials.core.EnhancedCelestialsContext.forLevel(EnhancedCelestialsContext.java:34)
	at net.minecraft.class_3218.handler$elf000$enhancedcelestials$injectLunarContext(class_3218.java:11730)
	at net.minecraft.class_3218.<init>(class_3218.java:263)
	at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java:359)
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:324)
	at net.minecraft.class_1132.method_3823(class_1132.java:69)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:646)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Niz09090** [comment]
me too in 1.20.1
https://paste.atlauncher.com/view/b28829fd-1ca7-474c-abcd-a497933d04d9

**Comment by darkneeed** [comment]
Me too

**Comment by CorgiTaco** [comment]
Fixed for versions 5.0.0.3 and beyond!
