### ISSUE TITLE
[Bug]: Description: Exception ticking world

### ISSUE THREAD

**Issue by vdjango** [CorgiTaco/Enhanced-Celestials#201]
### Minecraft Version

1.20.1

### Enhanced Celestials Version

Enhanced_Celestials-forge-1.20.1-5.0.0.3 | Enhanced_Celestials-forge-1.19-2.1.0.1 | Enhanced_Celestials-forge-1.19.2-2.1.0.5

### Mod Loader

Forge

### Mod Loader Version

47.2.32

### Bug Severity

Major

### What happened?

download Mohist https://mohistmc.com/downloadSoftware?project=mohist&projectVersion=1.20.1
Version=1.20.1
Forge: 47.2.32

------
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2024-05-11 18:36:50
Description: Exception ticking world

java.lang.IllegalStateException: Missing key in ResourceKey[minecraft:root / enhancedcelestials:lunar/event]: ResourceKey[enhancedcelestials:lunar/event / minecraft:enhancedcelestials-blood_moon]
	at net.minecraft.core.Registry.m_257106_(Registry.java:151) ~[server-1.20.1-20230612.114412-srg.jar%23204!/:?] {re:classloading}
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?] {re:mixin}
	at net.minecraft.core.Registry.m_246971_(Registry.java:151) ~[server-1.20.1-20230612.114412-srg.jar%23204!/:?] {re:classloading}
	at corgitaco.enhancedcelestials.lunarevent.LunarEventInstance.getEvent(LunarEventInstance.java:40) ~[【月亮事件】Enhanced_Celestials-forge-1.20.1-5.0.0.4.jar%23202!/:5.0.0.4] {re:classloading}
	at corgitaco.enhancedcelestials.lunarevent.LunarForecast.serverTick(LunarForecast.java:225) ~[【月亮事件】Enhanced_Celestials-forge-1.20.1-5.0.0.4.jar%23202!/:5.0.0.4] {re:mixin,re:classloading}
	at corgitaco.enhancedcelestials.lunarevent.LunarForecast.tick(LunarForecast.java:208) ~[【月亮事件】Enhanced_Celestials-forge-1.20.1-5.0.0.4.jar%23202!/:5.0.0.4] {re:mixin,re:classloading}
	at corgitaco.enhancedcelestials.core.EnhancedCelestialsContext.tick(EnhancedCelestialsContext.java:55) ~[【月亮事件】Enhanced_Celestials-forge-1.20.1-5.0.0.4.jar%23202!/:5.0.0.4] {re:mixin,re:classloading}
	at net.minecraft.server.level.ServerLevel.handler$zzg000$attachLunarTick(ServerLevel.java:1941) ~[server-1.20.1-20230612.114412-srg.jar%23204!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:enhancedcelestials.mixins.json:MixinServerWorld,pl:mixin:APP:corgilib.mixins.json:MixinServerLevel,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java) ~[server-1.20.1-20230612.114412-srg.jar%23204!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:enhancedcelestials.mixins.json:MixinServerWorld,pl:mixin:APP:corgilib.mixins.json:MixinServerLevel,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:1144) ~[server-1.20.1-20230612.114412-srg.jar%23204!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:349) ~[server-1.20.1-20230612.114412-srg.jar%23204!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:1060) ~[server-1.20.1-20230612.114412-srg.jar%23204!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:890) ~[server-1.20.1-20230612.114412-srg.jar%23204!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281) ~[server-1.20.1-20230612.114412-srg.jar%23204!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Suspected Mod: 
	Enhanced Celestials (enhancedcelestials), Version: 5.0.0.4
		Issue tracker URL: https://github.com/CorgiTaco/Enhanced-Celestials/issues
		at TRANSFORMER/enhancedcelestials@5.0.0.4/corgitaco.enhancedcelestials.lunarevent.LunarEventInstance.getEvent(LunarEventInstance.java:40)
Stacktrace:
	at net.minecraft.core.Registry.m_257106_(Registry.java:151) ~[server-1.20.1-20230612.114412-srg.jar%23204!/:?] {re:classloading}
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?] {re:mixin}
	at net.minecraft.core.Registry.m_246971_(Registry.java:151) ~[server-1.20.1-20230612.114412-srg.jar%23204!/:?] {re:classloading}
	at corgitaco.enhancedcelestials.lunarevent.LunarEventInstance.getEvent(LunarEventInstance.java:40) ~[【月亮事件】Enhanced_Celestials-forge-1.20.1-5.0.0.4.jar%23202!/:5.0.0.4] {re:classloading}
	at corgitaco.enhancedcelestials.lunarevent.LunarForecast.serverTick(LunarForecast.java:225) ~[【月亮事件】Enhanced_Celestials-forge-1.20.1-5.0.0.4.jar%23202!/:5.0.0.4] {re:mixin,re:classloading}
	at corgitaco.enhancedcelestials.lunarevent.LunarForecast.tick(LunarForecast.java:208) ~[【月亮事件】Enhanced_Celestials-forge-1.20.1-5.0.0.4.jar%23202!/:5.0.0.4] {re:mixin,re:classloading}
	at corgitaco.enhancedcelestials.core.EnhancedCelestialsContext.tick(EnhancedCelestialsContext.java:55) ~[【月亮事件】Enhanced_Celestials-forge-1.20.1-5.0.0.4.jar%23202!/:5.0.0.4] {re:mixin,re:classloading}
	at net.minecraft.server.level.ServerLevel.handler$zzg000$attachLunarTick(ServerLevel.java:1941) ~[server-1.20.1-20230612.114412-srg.jar%23204!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:enhancedcelestials.mixins.json:MixinServerWorld,pl:mixin:APP:corgilib.mixins.json:MixinServerLevel,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java) ~[server-1.20.1-20230612.114412-srg.jar%23204!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:enhancedcelestials.mixins.json:MixinServerWorld,pl:mixin:APP:corgilib.mixins.json:MixinServerLevel,pl:mixin:A}
-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: 2209
	Level dimension: minecraft:overworld
	Level spawn location: World: (208,64,32), Section: (at 0,0,0 in 13,4,2; chunk contains blocks 208,-64,32 to 223,319,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 1742 game time, 13001 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 11425 (now: false), thunder time: 99658 (now: false)
	Known server brands: mohist
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:1144) ~[server-1.20.1-20230612.114412-srg.jar%23204!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:349) ~[server-1.20.1-20230612.114412-srg.jar%23204!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:1060) ~[server-1.20.1-20230612.114412-srg.jar%23204!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:890) ~[server-1.20.1-20230612.114412-srg.jar%23204!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281) ~[server-1.20.1-20230612.114412-srg.jar%23204!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

-- System Details --
Details:
	Mohist Version: 1.20.1-719
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.2, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Microsoft
	Memory: 1741250968 bytes (1660 MiB) / 3363831808 bytes (3208 MiB) up to 17154703360 bytes (16360 MiB)
	CPUs: 20
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i9-10850K CPU @ 3.60GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 5
	Microarchitecture: unknown
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 10
	Number of logical CPUs: 20
	Graphics card #0 name: OrayIddDriver Device
	Graphics card #0 vendor: Shanghai Best Oray Information Technology Co., Ltd.
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: DriverVersion=17.1.58.818
	Graphics card #1 name: NVIDIA GeForce GTX 660
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 2048.00
	Graphics card #1 deviceId: 0x11c0
	Graphics card #1 versionInfo: DriverVersion=30.0.14.7141
	Memory slot #0 capacity (MB): 32768.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 32768.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 75161.61
	Virtual memory used (MB): 25137.18
	Swap memory total (MB): 9728.00
	Swap memory used (MB): 85.34
	JVM Flags: 0 total; 
	CraftBukkit Information: 
   Running: Mohist version 1.20.1-719 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) false
   Plugins: { Mohist v1.20.1 com.mohistmc.plugins.Main [],}
   Warnings: DEFAULT
   Reload Count: 0

### latest.log

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2024-05-11 18:36:50
Description: Exception ticking world

java.lang.IllegalStateException: Missing key in ResourceKey[minecraft:root / enhancedcelestials:lunar/event]: ResourceKey[enhancedcelestials:lunar/event / minecraft:enhancedcelestials-blood_moon]
	at net.minecraft.core.Registry.m_257106_(Registry.java:151) ~[server-1.20.1-20230612.114412-srg.jar%23204!/:?] {re:classloading}
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?] {re:mixin}
	at net.minecraft.core.Registry.m_246971_(Registry.java:151) ~[server-1.20.1-20230612.114412-srg.jar%23204!/:?] {re:classloading}
	at corgitaco.enhancedcelestials.lunarevent.LunarEventInstance.getEvent(LunarEventInstance.java:40) ~[【月亮事件】Enhanced_Celestials-forge-1.20.1-5.0.0.4.jar%23202!/:5.0.0.4] {re:classloading}
	at corgitaco.enhancedcelestials.lunarevent.LunarForecast.serverTick(LunarForecast.java:225) ~[【月亮事件】Enhanced_Celestials-forge-1.20.1-5.0.0.4.jar%23202!/:5.0.0.4] {re:mixin,re:classloading}
	at corgitaco.enhancedcelestials.lunarevent.LunarForecast.tick(LunarForecast.java:208) ~[【月亮事件】Enhanced_Celestials-forge-1.20.1-5.0.0.4.jar%23202!/:5.0.0.4] {re:mixin,re:classloading}
	at corgitaco.enhancedcelestials.core.EnhancedCelestialsContext.tick(EnhancedCelestialsContext.java:55) ~[【月亮事件】Enhanced_Celestials-forge-1.20.1-5.0.0.4.jar%23202!/:5.0.0.4] {re:mixin,re:classloading}
	at net.minecraft.server.level.ServerLevel.handler$zzg000$attachLunarTick(ServerLevel.java:1941) ~[server-1.20.1-20230612.114412-srg.jar%23204!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:enhancedcelestials.mixins.json:MixinServerWorld,pl:mixin:APP:corgilib.mixins.json:MixinServerLevel,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java) ~[server-1.20.1-20230612.114412-srg.jar%23204!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:enhancedcelestials.mixins.json:MixinServerWorld,pl:mixin:APP:corgilib.mixins.json:MixinServerLevel,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:1144) ~[server-1.20.1-20230612.114412-srg.jar%23204!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:349) ~[server-1.20.1-20230612.114412-srg.jar%23204!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:1060) ~[server-1.20.1-20230612.114412-srg.jar%23204!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:890) ~[server-1.20.1-20230612.114412-srg.jar%23204!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281) ~[server-1.20.1-20230612.114412-srg.jar%23204!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Suspected Mod: 
	Enhanced Celestials (enhancedcelestials), Version: 5.0.0.4
		Issue tracker URL: https://github.com/CorgiTaco/Enhanced-Celestials/issues
		at TRANSFORMER/enhancedcelestials@5.0.0.4/corgitaco.enhancedcelestials.lunarevent.LunarEventInstance.getEvent(LunarEventInstance.java:40)
Stacktrace:
	at net.minecraft.core.Registry.m_257106_(Registry.java:151) ~[server-1.20.1-20230612.114412-srg.jar%23204!/:?] {re:classloading}
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?] {re:mixin}
	at net.minecraft.core.Registry.m_246971_(Registry.java:151) ~[server-1.20.1-20230612.114412-srg.jar%23204!/:?] {re:classloading}
	at corgitaco.enhancedcelestials.lunarevent.LunarEventInstance.getEvent(LunarEventInstance.java:40) ~[【月亮事件】Enhanced_Celestials-forge-1.20.1-5.0.0.4.jar%23202!/:5.0.0.4] {re:classloading}
	at corgitaco.enhancedcelestials.lunarevent.LunarForecast.serverTick(LunarForecast.java:225) ~[【月亮事件】Enhanced_Celestials-forge-1.20.1-5.0.0.4.jar%23202!/:5.0.0.4] {re:mixin,re:classloading}
	at corgitaco.enhancedcelestials.lunarevent.LunarForecast.tick(LunarForecast.java:208) ~[【月亮事件】Enhanced_Celestials-forge-1.20.1-5.0.0.4.jar%23202!/:5.0.0.4] {re:mixin,re:classloading}
	at corgitaco.enhancedcelestials.core.EnhancedCelestialsContext.tick(EnhancedCelestialsContext.java:55) ~[【月亮事件】Enhanced_Celestials-forge-1.20.1-5.0.0.4.jar%23202!/:5.0.0.4] {re:mixin,re:classloading}
	at net.minecraft.server.level.ServerLevel.handler$zzg000$attachLunarTick(ServerLevel.java:1941) ~[server-1.20.1-20230612.114412-srg.jar%23204!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:enhancedcelestials.mixins.json:MixinServerWorld,pl:mixin:APP:corgilib.mixins.json:MixinServerLevel,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java) ~[server-1.20.1-20230612.114412-srg.jar%23204!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:enhancedcelestials.mixins.json:MixinServerWorld,pl:mixin:APP:corgilib.mixins.json:MixinServerLevel,pl:mixin:A}
-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: 2209
	Level dimension: minecraft:overworld
	Level spawn location: World: (208,64,32), Section: (at 0,0,0 in 13,4,2; chunk contains blocks 208,-64,32 to 223,319,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 1742 game time, 13001 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 11425 (now: false), thunder time: 99658 (now: false)
	Known server brands: mohist
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:1144) ~[server-1.20.1-20230612.114412-srg.jar%23204!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:349) ~[server-1.20.1-20230612.114412-srg.jar%23204!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:1060) ~[server-1.20.1-20230612.114412-srg.jar%23204!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:890) ~[server-1.20.1-20230612.114412-srg.jar%23204!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281) ~[server-1.20.1-20230612.114412-srg.jar%23204!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

-- System Details --
Details:
	Mohist Version: 1.20.1-719
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.2, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Microsoft
	Memory: 1741250968 bytes (1660 MiB) / 3363831808 bytes (3208 MiB) up to 17154703360 bytes (16360 MiB)
	CPUs: 20
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i9-10850K CPU @ 3.60GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 5
	Microarchitecture: unknown
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 10
	Number of logical CPUs: 20
	Graphics card #0 name: OrayIddDriver Device
	Graphics card #0 vendor: Shanghai Best Oray Information Technology Co., Ltd.
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: DriverVersion=17.1.58.818
	Graphics card #1 name: NVIDIA GeForce GTX 660
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 2048.00
	Graphics card #1 deviceId: 0x11c0
	Graphics card #1 versionInfo: DriverVersion=30.0.14.7141
	Memory slot #0 capacity (MB): 32768.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 32768.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 75161.61
	Virtual memory used (MB): 25137.18
	Swap memory total (MB): 9728.00
	Swap memory used (MB): 85.34
	JVM Flags: 0 total; 
	CraftBukkit Information: 
   Running: Mohist version 1.20.1-719 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) false
   Plugins: { Mohist v1.20.1 com.mohistmc.plugins.Main [],}
   Warnings: DEFAULT
   Reload Count: 0

**Comment by CorgiTaco** [comment]
Enhanced Celestials will not support projects that support plug-ins due to their hacky nature.
