### ISSUE TITLE
[Crash]: Unsure what caused this on the server

### ISSUE THREAD

**Issue by Camawama** [CorgiTaco/Enhanced-Celestials#205]
### Minecraft Version

1.20.1

### Enhanced Celestials Version

5.0.0.4

### Mod Loader

Forge

### Mod Loader Version

47.2.30

### What happened?

Two players randomly crashed at the same time on the server. They were sent instantly to the launcher with no crash report. Below is the log from one of the players.

`[21:06:26] [Render thread/ERROR]: Unreported exception thrown!
java.lang.IllegalStateException: Not filled all elements of the vertex
	at com.mojang.blaze3d.vertex.BufferBuilder.m_5752_(BufferBuilder.java:264) ~[client-1.20.1-20230612.114412-srg.jar%23609!/:?]
	at net.povstalec.stellarview.api.celestials.CelestialObject.renderObject(CelestialObject.java:216) ~[Stellar%20View-1.20.1-0.2.4.jar%23575!/:0.2.4]
	at net.povstalec.stellarview.api.celestials.CelestialObject.render(CelestialObject.java:279) ~[Stellar%20View-1.20.1-0.2.4.jar%23575!/:0.2.4]
	at net.povstalec.stellarview.api.celestials.orbiting.OrbitingCelestialObject.render(OrbitingCelestialObject.java:114) ~[Stellar%20View-1.20.1-0.2.4.jar%23575!/:0.2.4]
	at net.povstalec.stellarview.api.celestials.StarField.lambda$render$0(StarField.java:149) ~[Stellar%20View-1.20.1-0.2.4.jar%23575!/:0.2.4]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at net.povstalec.stellarview.api.celestials.StarField.render(StarField.java:143) ~[Stellar%20View-1.20.1-0.2.4.jar%23575!/:0.2.4]
	at net.povstalec.stellarview.api.celestials.orbiting.OrbitingCelestialObject.renderFrom(OrbitingCelestialObject.java:145) ~[Stellar%20View-1.20.1-0.2.4.jar%23575!/:0.2.4]
	at net.povstalec.stellarview.api.celestials.orbiting.OrbitingCelestialObject.renderFrom(OrbitingCelestialObject.java:133) ~[Stellar%20View-1.20.1-0.2.4.jar%23575!/:0.2.4]
	at net.povstalec.stellarview.api.celestials.orbiting.Planet.renderLocalSky(Planet.java:106) ~[Stellar%20View-1.20.1-0.2.4.jar%23575!/:0.2.4]
	at net.povstalec.stellarview.client.render.level.StellarViewSky.renderEcliptic(StellarViewSky.java:66) ~[Stellar%20View-1.20.1-0.2.4.jar%23575!/:0.2.4]
	at net.povstalec.stellarview.client.render.level.StellarViewSky.renderSky(StellarViewSky.java:93) ~[Stellar%20View-1.20.1-0.2.4.jar%23575!/:0.2.4]
	at net.povstalec.stellarview.api.StellarViewSpecialEffects.renderSky(StellarViewSpecialEffects.java:58) ~[Stellar%20View-1.20.1-0.2.4.jar%23575!/:0.2.4]
	at net.povstalec.stellarview.client.render.level.StellarViewOverworldEffects.renderSky(StellarViewOverworldEffects.java:234) ~[Stellar%20View-1.20.1-0.2.4.jar%23575!/:0.2.4]
	at net.minecraft.client.renderer.LevelRenderer.m_202423_(LevelRenderer.java:1774) ~[client-1.20.1-20230612.114412-srg.jar%23609!/:?]
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1155) ~[client-1.20.1-20230612.114412-srg.jar%23609!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1126) ~[client-1.20.1-20230612.114412-srg.jar%23609!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:909) ~[client-1.20.1-20230612.114412-srg.jar%23609!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23609!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23609!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.2.30.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.30.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.30.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.30.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]`

### crash-log

NO CRASH REPORT, PLAYERS INSTANTLY GOT SENT TO LAUNCHER WITH NO CRASH

### latest.log

[latest (1).log](https://github.com/CorgiTaco/Enhanced-Celestials/files/15492764/latest.1.log)

**Comment by CorgiTaco** [comment]
This is a crash from another mod called `stellarview` not this one. I dont change rendering at all in a way that uses vertex builders
