### ISSUE TITLE
Commands do not work in command blocks or datapacks

### ISSUE THREAD

**Issue by 1FoxInTheBox1** [CorgiTaco/Enhanced-Celestials#49]
Attempting to use a command block or datapack to activate a bloodmoon causes an error. When making a datapack using the command and using /reload the game output shows this error

Failed to load function disc_quest:test
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Whilst parsing command on line 1: Unknown or incomplete command, see below for error at position 0: <--[HERE]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1584)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1574)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.IllegalArgumentException: Whilst parsing command on line 1: Unknown or incomplete command, see below for error at position 0: <--[HERE]
	at net.minecraft.command.FunctionObject.func_237140_a_(SourceFile:62)
	at net.minecraft.resources.FunctionReloader.func_240935_a_(SourceFile:86)
	at net.minecraft.resources.FunctionReloader$$Lambda$10805/656821543.get(Unknown Source)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1582)
	... 5 more
	
I should note that I am using version 1.0.4 on minecraft 1.16.5 and forge 36.1.4, and that the command works properly when used by a player until /reload is used, after which the command is no longer recognized no matter what activates it.

**Comment by stingie** [comment]
Seconding this, can confirm that commands will not run in command blocks.

**Comment by Luke-Acuff** [comment]
Same issue, 1.19.2

Should note that it seems like they DO work in multiplayer if function permissions level is set to 4 in server.properties. Hopefully an easy fix!

**Comment by CorgiTaco** [comment]
Should be fixed in the latest 1.19 version,

Get it here: 
Forge: https://www.curseforge.com/minecraft/mc-mods/enhanced-celestials/files/4392661 / https://modrinth.com/mod/enhanced-celestials/version/1.19.2-2.1.0.4-forge
Fabric: https://www.curseforge.com/minecraft/mc-mods/enhanced-celestials-fabric/files/4392659 / https://modrinth.com/mod/enhanced-celestials/version/1.19.2-2.1.0.4-fabric
