### ISSUE TITLE
Crashes on 1.16.5 

### ISSUE THREAD

**Issue by reemays** [CorgiTaco/Enhanced-Celestials#52]
I have below crashes when loading the Enhanced Celestials 1.0.2 version.

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 7/29/21 2:53 PM
Description: Initializing game

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.class_757.<init>(class_757.java:159)
	at net.minecraft.class_310.<init>(class_310.java:533)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in net/minecraft/class_765::method_3313(F)V has incompatible changes at opcode 183 in callback net/minecraft/class_765::doOurLightMap.
Expected: [Lnet/minecraft/class_638;, F, F, F, Lnet/minecraft/class_1160;]
   Found: [Lnet/minecraft/class_638;, F, F, F, F]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:497)
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:447)
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:264)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:385)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1284)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 16 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.class_757.<init>(class_757.java:159)
	at net.minecraft.class_310.<init>(class_310.java:533)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_261, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 7297437688 bytes (6959 MB) / 7918845952 bytes (7552 MB) up to 7918845952 bytes (7552 MB)
	CPUs: 4
	JVM Flags: 10 total; -Xmn128M -Xmx7526M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		amecsapi: Amecs API 1.1.4+mc1.16.5
		angerable-patch: Angerable Patch 1.1.0-1.16.4
		autoconfig1u: Auto Config v1 Updated 3.3.1
		autoconfigtoml: AutoConfig-TOML 1.0.0-fabric
		backslot: BackSlot 1.1.11
		backslotaddon: BackSlot Addon 1.0.3
		bendy-lib: Bendy api 1.1.0
		bettercaves: YUNG's Better Caves 1.16.2-1.0.3
		betterend: Better End 0.9.1-pre
		bettermineshafts: YUNG's Better Mineshafts 1.16.4-1.0.1
		betternether: Better Nether 5.0.7
		betterpingdisplay: Better Ping Display 1.1
		blue_endless_jankson: jankson 1.2.0
		cardinal-components: Cardinal Components API 2.8.3
		cardinal-components-base: Cardinal Components API (base) 2.8.3
		cardinal-components-block: Cardinal Components API (blocks) 2.8.3
		cardinal-components-chunk: Cardinal Components API (chunks) 2.8.3
		cardinal-components-entity: Cardinal Components API (entities) 2.8.3
		cardinal-components-item: Cardinal Components API (items) 2.8.3
		cardinal-components-level: Cardinal Components API (world saves) 2.8.3
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.8.3
		cardinal-components-util: Cardinal Components API (utilities) 2.8.3
		cardinal-components-world: Cardinal Components API (worlds) 2.8.3
		carpet: Carpet Mod in Fabric 1.4.30
		charm: Charm 2.2.0
		charmonium: Charmonium 2.2.2
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.4.5
		cloth-config2: Cloth Config v4 4.11.17
		com_electronwill_night-config_core: core 3.6.3
		com_electronwill_night-config_toml: toml 3.6.3
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		dark-loading-screen: Dark Loading Screen 1.6.2
		de_javagl_obj: obj 0.3.0
		diggusmaximus: Diggus Maximus 1.4.2-1.16.3
		dual_riders: DualRiders 1.0.5
		earthtojavamobs: Earth2Java 1.7.1+1.16.4
		emotecraft: Emotecraft 2.0.9
		enhancedcelestials: Enhanced Celestials 1.0.2
		entityculling: EntityCulling-Fabric 1.2.2
		fabric: Fabric API 0.37.0+1.16
		fabric-api-base: Fabric API Base 0.3.0+c88702897d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+6aebe11a7d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.10+3661eaa17d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.6+61336ba97d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+c88702897d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.3+f941baf07d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.3.0+bc7a746f7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.3+e3c9d0627d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.5+c88702897d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+f3e8589e7d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.0+2868a2287d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+2868a2287d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.6+2868a2287d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.11+ca0ef93d7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.7+8183d3957d
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.0.0+5f6b94517d
		fabricloader: Fabric Loader 0.11.3
		ferritecore: FerriteCore 2.0.4
		fiber: fiber 0.23.0-2
		figura: Figura 0.0.5
		hungyvillager: Hungy Villager 1.0.0
		illuminations: Illuminations 1.4.9
		infinityfix: Infinity Fix 1.1.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		justmap-unlimited: Just Map Unlimited 1.2.15
		kyrptconfig: Kytpt Config 1.1.4-1.16
		minecraft: Minecraft 1.16.5
		mm: Manningham Mills 2.1
		mo_glass: Mo Glass 1.5-MC1.16.5
		modmenu: Mod Menu 1.16.8
		mostructures: Mo' Structures 1.1.0+mc.1.16.5
		npcvariety: NPC Variety 1.2.4
		offlineskins: OfflineSkins 1.16.5-v1-fabric
		optifabric: OptiFabric 1.9.2
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_luaj_luaj-jse: luaj-jse 3.0.1
		patchouli: Patchouli 1.16.4-50-FABRIC
		randompatches: RandomPatches 2.4.5-fabric
		repurposed_structures: Repurposed Structures 1.16.5-1.9.0
		roughlyenoughitems: Roughly Enough Items 5.8.12
		roughlyenoughitems-api: REI (API) 5.8.12
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.8.12
		roughlyenoughitems-runtime: REI (Runtime) 5.8.12
		seasons: Fabric Seasons 1.2-BETA
		show-off: Show Off 1.0.0-1.16.5
		spark: spark 1.5.2
		spruceui: SpruceUI 2.1.4+1.16
		starlight: Starlight fabric-1.0.0-RC1-59d1f21
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 1.0.3
		terraform-config-api-v1: Terraform Config API (v1) 1.0.2
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 1.0.2
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 1.0.2
		terraform-tree-api-v1: Terraform Tree API (v1) 1.0.3
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.2
		tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2
		torohealth: ToroHealth Damage Indicators 1.16.4-fabric-4
		traverse: Traverse 3.3.2
		vanguard: Vanguard 1.0.5
		voyager: Voyager 1.0.0
		waila: Hwyla 1.9.22
		yungsapi: YUNG's API 1.16.5-Fabric-2
	Patchouli open book context: n/a
	Launched Version: fabric-loader-0.11.3-1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1050/PCIe/SSE2 GL version 4.6.0 NVIDIA 445.87, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 4x Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
	OptiFine Version: OptiFine_1.16.5_HD_U_G7
	OptiFine Build: 20210305-003221
	Render Distance Chunks: 17
	Mipmaps: 3
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: BSL_v7.2.01pre2.zip
	OpenGlVersion: 4.6.0 NVIDIA 445.87
	OpenGlRenderer: GeForce GTX 1050/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.16.5
	OptiFine jar version: OptiFine_1.16.5_HD_U_G7
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: C:\Users\MSI GL62\AppData\Roaming\.minecraft\.optifine\OptiFine_1.16.5_HD_U_G7\Optifine-mapped.jar
	OptiFabric error: <None>

**Comment by CorgiTaco** [comment]
Fixed: https://www.curseforge.com/minecraft/mc-mods/enhanced-celestials-fabric/files/3432024
